name: Build & Push (GHCR, multi-arch)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}  # manual trigger

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/seetharamacharyulu/itosm-platform:latest
            ghcr.io/seetharamacharyulu/itosm-platform:${{ github.sha }}
